[General]
# How long to stay in pairable mode before going back to non-discoverable
# The value is in seconds. Default is 0.
# 0 = disable timer, i.e. stay pairable forever
PairableTimeout=0
# Always allow pairing even if there are no agent registered
# Possible values: true, false
# Default: false
AlwaysPairable=true

[Policy]
AutoEnable=true
