monitor.bluez.rules = [
  {
    matches = [
      {
        node.name = "~bluez_.*"
      }
    ]
    actions = {
      update-props = {
        target.object = "unified-upmix"
        channelmix.upmix = true
        channelmix.upmix-method = psd
        channelmix.rear-delay = 12.0
      }
    }
  }
]
