context.modules = [
{   name = libpipewire-module-loopback
    args = {
        node.description = "Local Upmix 4.1"
        audio.position = [ FL FR FC LFE RL RR ]
        capture.props = {
            node.name = "local-upmix"
            media.class = Audio/Sink
            node.priority.driver = 1000
            node.priority.session = 1000
        }
        playback.props = {
            node.name = "local-upmix-output"
            audio.position = [ FL FR RL RR LFE ]
            target.object = "alsa_output.usb-0d8c_USB_Sound_Device-00.analog-surround-51"
            node.passive = true
            stream.dont-remix = true
            channelmix.upmix = true
            channelmix.upmix-method = psd
            channelmix.lfe-cutoff = 150
            channelmix.rear-delay = 12.0
        }
    }
}
]
