general =
{
    name = "opti";
    output_backend = "pipewire";
    interpolation = "soxr";
    allow_session_interruption = "yes";
    session_timeout = 120;
};

pipewire =
{
    application_name = "Shairport Sync";
    node_name = "shairport-sync";
};

sessioncontrol =
{
    allow_session_interruption = "yes";
    session_timeout = 120;
};

metadata =
{
    enabled = "yes";
    include_cover_art = "yes";
};
