context.modules = [
{   name = libpipewire-module-loopback
    args = {
        node.description = "VBAN Upmix 4.1"
        audio.position = [ FL FR ]
        capture.props = {
            node.name = "vban-upmix"
            media.class = Audio/Sink
        }
        playback.props = {
            node.name = "vban-upmix-output"
            audio.position = [ FL FR RL RR FC LFE ]
            target.object = "alsa_output.usb-0d8c_USB_Sound_Device-00.pro-output-0"
            node.passive = true
            stream.dont-remix = true
            channelmix.upmix = true
            channelmix.upmix-method = psd
            channelmix.lfe-cutoff = 150
            channelmix.fc-cutoff = 12000
            channelmix.rear-delay = 12.0
        }
    }
}
]
