context.modules = [
{   name = libpipewire-module-vban-recv
    args = {
        source.ip = "0.0.0.0"
        source.port = 6980
        sess.latency.msec = 100
        stream.props = {
            node.name = "vban-recv"
            target.object = "vban-upmix"
            node.dont-fallback = true
        }
        stream.rules = [
            {   matches = [
                    {    sess.name = "~.*"
                    }
                ]
                actions = {
                    create-stream = {
                        stream.props = {
                            target.object = "vban-upmix"
                            node.dont-fallback = true
                        }
                    }
                }
            }
        ]
    }
}
]
