context.modules = [
    {
        name = libpipewire-module-vban-recv
        args = {
            source.ip = 0.0.0.0
            source.port = 6980
            sess.latency.msec = 20
            node.always-process = true
            stream.rules = [
                {
                    matches = [
                        { sess.name = "~.*" }
                    ]
                    actions = {
                        create-stream = {
                            target.object = "unified-upmix"
                            audio.position = [ FL FR FC LFE RL RR ]
                            media.class = "Stream/Output/Audio"
                            node.name = "vban-receiver"
                        }
                    }
                }
            ]
        }
    }
]
